name: ypay
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:    
    sdk: flutter
  sqflite: ^1.3.1
  path_provider: ^0.5.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_auth_buttons: ^0.8.0
  flutter_facebook_login: ^3.0.0
  http: ^0.12.1
  flushbar: 1.9.1
  google_sign_in: ^4.5.1
  google_sign_in_web: 0.9.1
  flutter_spinkit: "^2.1.0"
  flutter_i18n: ^0.5.0
  intl_translation: ^0.17.1
  provider: ^3.1.0
  shared_preferences: ^0.5.7+3
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  numeric_keyboard: ^1.0.0
  flutter_phoenix: ^0.1.0
  carousel_slider: ^2.2.1
  country_icons: ^1.1.1
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0+1
  flutter_screenutil: ^2.1.0
  build_runner: ^1.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/lightbulb.png
   - images/bulb.jpg
   - images/faces.jpg
   - images/wechat.png
   - images/google.jpg
   - images/chinaRound.png
   - images/mmRound.png
   - images/usaRound.png

   - i18n/en.json
   - i18n/mm.json
   - i18n/zh.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: EucrosiaUPC
      fonts:
        - asset: fonts/upcel.ttf
        # - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: Roboto Slab Regular
      fonts:
        - asset: fonts/RobotoSlab.ttf
    - family: myanmar3
      fonts:
        - asset: fonts/Myanmar3_MultiOS.ttf
    - family: pyidaungsu
      fonts:
        - asset: fonts/Pyidaungsu-2_5_3_Regular.ttf
        - asset: fonts/Pyidaungsu_2_5_3_Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
